// Code generated by genrules from EN16931-CII-model.sch; DO NOT EDIT.
// Source: https://github.com/ConnectingEurope/eInvoicing-EN16931
// Version: v1.3.14.1
// Generated: 2025-10-07T12:31:26Z

package rules

// Rule represents a business rule from the EN 16931 specification.
type Rule struct {
	Code        string
	Fields      []string
	Description string
}

var (
	BR1 = Rule{
		Code:        "BR-01",
		Fields:      []string{"BT-24"},
		Description: `An Invoice shall have a Specification identifier (BT-24).`,
	}
	BR2 = Rule{
		Code:        "BR-02",
		Fields:      []string{"BT-1"},
		Description: `An Invoice shall have an Invoice number (BT-1).`,
	}
	BR3 = Rule{
		Code:        "BR-03",
		Fields:      []string{"BT-2"},
		Description: `An Invoice shall have an Invoice issue date (BT-2).`,
	}
	BR4 = Rule{
		Code:        "BR-04",
		Fields:      []string{"BT-3"},
		Description: `An Invoice shall have an Invoice type code (BT-3).`,
	}
	BR5 = Rule{
		Code:        "BR-05",
		Fields:      []string{"BT-5"},
		Description: `An Invoice shall have an Invoice currency code (BT-5).`,
	}
	BR6 = Rule{
		Code:        "BR-06",
		Fields:      []string{"BT-27"},
		Description: `An Invoice shall contain the Seller name (BT-27).`,
	}
	BR7 = Rule{
		Code:        "BR-07",
		Fields:      []string{"BT-44"},
		Description: `An Invoice shall contain the Buyer name (BT-44).`,
	}
	BR8 = Rule{
		Code:        "BR-08",
		Fields:      []string{"BG-5"},
		Description: `An Invoice shall contain the Seller postal address (BG-5).`,
	}
	BR9 = Rule{
		Code:        "BR-09",
		Fields:      []string{"BG-5", "BT-40"},
		Description: `The Seller postal address (BG-5) shall contain a Seller country code (BT-40).`,
	}
	BR10 = Rule{
		Code:        "BR-10",
		Fields:      []string{"BG-8"},
		Description: `An Invoice shall contain the Buyer postal address (BG-8).`,
	}
	BR11 = Rule{
		Code:        "BR-11",
		Fields:      []string{"BT-55"},
		Description: `The Buyer postal address shall contain a Buyer country code (BT-55).`,
	}
	BR12 = Rule{
		Code:        "BR-12",
		Fields:      []string{"BT-106"},
		Description: `An Invoice shall have the Sum of Invoice line net amount (BT-106).`,
	}
	BR13 = Rule{
		Code:        "BR-13",
		Fields:      []string{"BT-109"},
		Description: `An Invoice shall have the Invoice total amount without VAT (BT-109).`,
	}
	BR14 = Rule{
		Code:        "BR-14",
		Fields:      []string{"BT-112"},
		Description: `An Invoice shall have the Invoice total amount with VAT (BT-112).`,
	}
	BR15 = Rule{
		Code:        "BR-15",
		Fields:      []string{"BT-115"},
		Description: `An Invoice shall have the Amount due for payment (BT-115).`,
	}
	BR16 = Rule{
		Code:        "BR-16",
		Fields:      []string{"BG-25"},
		Description: `An Invoice shall have at least one Invoice line (BG-25).`,
	}
	BR17 = Rule{
		Code:        "BR-17",
		Fields:      []string{"BG-10", "BG-4", "BT-59"},
		Description: `The Payee name (BT-59) shall be provided in the Invoice, if the Payee (BG-10) is different from the Seller (BG-4).`,
	}
	BR18 = Rule{
		Code:        "BR-18",
		Fields:      []string{"BG-11", "BG-4", "BT-62"},
		Description: `The Seller tax representative name (BT-62) shall be provided in the Invoice, if the Seller (BG-4) has a Seller tax representative party (BG-11).`,
	}
	BR19 = Rule{
		Code:        "BR-19",
		Fields:      []string{"BG-11", "BG-12", "BG-4"},
		Description: `The Seller tax representative postal address (BG-12) shall be provided in the Invoice, if the Seller (BG-4) has a Seller tax representative party (BG-11).`,
	}
	BR20 = Rule{
		Code:        "BR-20",
		Fields:      []string{"BG-11", "BG-12", "BG-4", "BT-69"},
		Description: `The Seller tax representative postal address (BG-12) shall contain a Tax representative country code (BT-69), if the Seller (BG-4) has a Seller tax representative party (BG-11).`,
	}
	BR21 = Rule{
		Code:        "BR-21",
		Fields:      []string{"BG-25", "BT-126"},
		Description: `Each Invoice line (BG-25) shall have an Invoice line identifier (BT-126).`,
	}
	BR22 = Rule{
		Code:        "BR-22",
		Fields:      []string{"BG-25", "BT-129"},
		Description: `Each Invoice line (BG-25) shall have an Invoiced quantity (BT-129).`,
	}
	BR23 = Rule{
		Code:        "BR-23",
		Fields:      []string{"BG-25", "BT-130"},
		Description: `An Invoice line (BG-25) shall have an Invoiced quantity unit of measure code (BT-130).`,
	}
	BR24 = Rule{
		Code:        "BR-24",
		Fields:      []string{"BG-25", "BT-131"},
		Description: `Each Invoice line (BG-25) shall have an Invoice line net amount (BT-131).`,
	}
	BR25 = Rule{
		Code:        "BR-25",
		Fields:      []string{"BG-25", "BT-153"},
		Description: `Each Invoice line (BG-25) shall contain the Item name (BT-153).`,
	}
	BR26 = Rule{
		Code:        "BR-26",
		Fields:      []string{"BG-25", "BT-146"},
		Description: `Each Invoice line (BG-25) shall contain the Item net price (BT-146).`,
	}
	BR27 = Rule{
		Code:        "BR-27",
		Fields:      []string{"BT-146"},
		Description: `The Item net price (BT-146) shall NOT be negative.`,
	}
	BR28 = Rule{
		Code:        "BR-28",
		Fields:      []string{"BT-148"},
		Description: `The Item gross price (BT-148) shall NOT be negative.`,
	}
	BR29 = Rule{
		Code:        "BR-29",
		Fields:      []string{"BT-73", "BT-74"},
		Description: `If both Invoicing period start date (BT-73) and Invoicing period end date (BT-74) are given then the Invoicing period end date (BT-74) shall be later or equal to the Invoicing period start date (BT-73).`,
	}
	BR30 = Rule{
		Code:        "BR-30",
		Fields:      []string{"BT-134", "BT-135"},
		Description: `If both Invoice line period start date (BT-134) and Invoice line period end date (BT-135) are given then the Invoice line period end date (BT-135) shall be later or equal to the Invoice line period start date (BT-134).`,
	}
	BR31 = Rule{
		Code:        "BR-31",
		Fields:      []string{"BG-20", "BT-92"},
		Description: `Each Document level allowance (BG-20) shall have a Document level allowance amount (BT-92).`,
	}
	BR32 = Rule{
		Code:        "BR-32",
		Fields:      []string{"BG-20", "BT-95"},
		Description: `Each Document level allowance (BG-20) shall have a Document level allowance VAT category code (BT-95).`,
	}
	BR33 = Rule{
		Code:        "BR-33",
		Fields:      []string{"BG-20", "BT-97", "BT-98"},
		Description: `Each Document level allowance (BG-20) shall have a Document level allowance reason (BT-97) or a Document level allowance reason code (BT-98).`,
	}
	BR36 = Rule{
		Code:        "BR-36",
		Fields:      []string{"BG-21", "BT-99"},
		Description: `Each Document level charge (BG-21) shall have a Document level charge amount (BT-99).`,
	}
	BR37 = Rule{
		Code:        "BR-37",
		Fields:      []string{"BG-21", "BT-102"},
		Description: `Each Document level charge (BG-21) shall have a Document level charge VAT category code (BT-102).`,
	}
	BR38 = Rule{
		Code:        "BR-38",
		Fields:      []string{"BG-21", "BT-104", "BT-105"},
		Description: `Each Document level charge (BG-21) shall have a Document level charge reason (BT-104) or a Document level charge reason code (BT-105).`,
	}
	BR41 = Rule{
		Code:        "BR-41",
		Fields:      []string{"BG-27", "BT-136"},
		Description: `Each Invoice line allowance (BG-27) shall have an Invoice line allowance amount (BT-136).`,
	}
	BR42 = Rule{
		Code:        "BR-42",
		Fields:      []string{"BG-27", "BT-139", "BT-140"},
		Description: `Each Invoice line allowance (BG-27) shall have an Invoice line allowance reason (BT-139) or an Invoice line allowance reason code (BT-140).`,
	}
	BR43 = Rule{
		Code:        "BR-43",
		Fields:      []string{"BG-28", "BT-141"},
		Description: `Each Invoice line charge (BG-28) shall have an Invoice line charge amount (BT-141).`,
	}
	BR44 = Rule{
		Code:        "BR-44",
		Fields:      []string{"BG-28", "BT-144", "BT-145"},
		Description: `Each Invoice line charge (BG-28) shall have an Invoice line charge reason (BT-144) or an Invoice line charge reason code (BT-145).`,
	}
	BR45 = Rule{
		Code:        "BR-45",
		Fields:      []string{"BG-23", "BT-116"},
		Description: `Each VAT breakdown (BG-23) shall have a VAT category taxable amount (BT-116).`,
	}
	BR46 = Rule{
		Code:        "BR-46",
		Fields:      []string{"BG-23", "BT-117"},
		Description: `Each VAT breakdown (BG-23) shall have a VAT category tax amount (BT-117).`,
	}
	BR47 = Rule{
		Code:        "BR-47",
		Fields:      []string{"BG-23", "BT-118"},
		Description: `Each VAT breakdown (BG-23) shall be defined through a VAT category code (BT-118).`,
	}
	BR48 = Rule{
		Code:        "BR-48",
		Fields:      []string{"BG-23", "BT-119"},
		Description: `Each VAT breakdown (BG-23) shall have a VAT category rate (BT-119), except if the Invoice is not subject to VAT.`,
	}
	BR49 = Rule{
		Code:        "BR-49",
		Fields:      []string{"BG-16", "BT-81"},
		Description: `A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).`,
	}
	BR50 = Rule{
		Code:        "BR-50",
		Fields:      []string{"BG-16", "BT-84"},
		Description: `A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.`,
	}
	BR51 = Rule{
		Code:        "BR-51",
		Fields:      []string{"BT-97"},
		Description: `In accordance with card payments security standards an invoice should never include a full card primary account number (BT-97). At the moment PCI Security Standards Council has defined that the first 6 digits and last 4 digits are the maximum number of digits to be shown.`,
	}
	BR52 = Rule{
		Code:        "BR-52",
		Fields:      []string{"BG-24", "BT-122"},
		Description: `Each Additional supporting document (BG-24) shall contain a Supporting document reference (BT-122).`,
	}
	BR53 = Rule{
		Code:        "BR-53",
		Fields:      []string{"BT-111", "BT-6"},
		Description: `If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.`,
	}
	BR54 = Rule{
		Code:        "BR-54",
		Fields:      []string{"BG-32", "BT-160", "BT-161"},
		Description: `Each Item attribute (BG-32) shall contain an Item attribute name (BT-160) and an Item attribute value (BT-161).`,
	}
	BR55 = Rule{
		Code:        "BR-55",
		Fields:      []string{"BG-3", "BT-25"},
		Description: `Each Preceding Invoice reference (BG-3) shall contain a Preceding Invoice reference (BT-25).`,
	}
	BR56 = Rule{
		Code:        "BR-56",
		Fields:      []string{"BG-11", "BT-63"},
		Description: `Each Seller tax representative party (BG-11) shall have a Seller tax representative VAT identifier (BT-63).`,
	}
	BR57 = Rule{
		Code:        "BR-57",
		Fields:      []string{"BG-15", "BT-80"},
		Description: `Each Deliver to address (BG-15) shall contain a Deliver to country code (BT-80).`,
	}
	BR61 = Rule{
		Code:        "BR-61",
		Fields:      []string{"BT-81", "BT-84"},
		Description: `If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.`,
	}
	BR62 = Rule{
		Code:        "BR-62",
		Fields:      []string{"BT-34"},
		Description: `The Seller electronic address (BT-34) shall have a Scheme identifier.`,
	}
	BR63 = Rule{
		Code:        "BR-63",
		Fields:      []string{"BT-49"},
		Description: `The Buyer electronic address (BT-49) shall have a Scheme identifier.`,
	}
	BR64 = Rule{
		Code:        "BR-64",
		Fields:      []string{"BT-157"},
		Description: `The Item standard identifier (BT-157) shall have a Scheme identifier.`,
	}
	BR65 = Rule{
		Code:        "BR-65",
		Fields:      []string{"BT-158"},
		Description: `The Item classification identifier (BT-158) shall have a Scheme identifier.`,
	}
	BR66 = Rule{
		Code:        "BR-66",
		Fields:      []string{"BG-20", "BG-21"},
		Description: `Each Specified Trade Allowance Charge (BG-20)(BG-21) shall contain a Charge Indicator.`,
	}
	BRAE1 = Rule{
		Code:        "BR-AE-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Reverse charge" shall contain in the VAT breakdown (BG-23) exactly one VAT category code (BT-118) equal with "VAT reverse charge".`,
	}
	BRAE2 = Rule{
		Code:        "BR-AE-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Reverse charge" shall contain the Seller VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal registration identifier (BT-47).`,
	}
	BRAE3 = Rule{
		Code:        "BR-AE-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Reverse charge" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal registration identifier (BT-47).`,
	}
	BRAE4 = Rule{
		Code:        "BR-AE-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Reverse charge" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal registration identifier (BT-47).`,
	}
	BRAE5 = Rule{
		Code:        "BR-AE-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Reverse charge" the Invoiced item VAT rate (BT-152) shall be 0 (zero).`,
	}
	BRAE6 = Rule{
		Code:        "BR-AE-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Reverse charge" the Document level allowance VAT rate (BT-96) shall be 0 (zero).`,
	}
	BRAE7 = Rule{
		Code:        "BR-AE-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Reverse charge" the Document level charge VAT rate (BT-103) shall be 0 (zero).`,
	}
	BRAE8 = Rule{
		Code:        "BR-AE-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Reverse charge" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Reverse charge".`,
	}
	BRAE9 = Rule{
		Code:        "BR-AE-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Reverse charge" shall be 0 (zero).`,
	}
	BRAE10 = Rule{
		Code:        "BR-AE-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Reverse charge" shall have a VAT exemption reason code (BT-121), meaning "Reverse charge" or the VAT exemption reason text (BT-120) "Reverse charge" (or the equivalent standard text in another language).`,
	}
	BRAF1 = Rule{
		Code:        "BR-AF-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "IGIC" shall contain in the VAT breakdown (BG-23) at least one VAT category code (BT-118) equal with "IGIC".`,
	}
	BRAF2 = Rule{
		Code:        "BR-AF-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "IGIC" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAF3 = Rule{
		Code:        "BR-AF-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "IGIC" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAF4 = Rule{
		Code:        "BR-AF-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "IGIC" shall contain the Seller VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAF5 = Rule{
		Code:        "BR-AF-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "IGIC" the invoiced item VAT rate (BT-152) shall be greater than 0 (zero).`,
	}
	BRAF6 = Rule{
		Code:        "BR-AF-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "IGIC" the Document level allowance VAT rate (BT-96) shall be 0 (zero) or greater than zero.`,
	}
	BRAF7 = Rule{
		Code:        "BR-AF-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "IGIC" the Document level charge VAT rate (BT-103) shall be 0 (zero) or greater than zero.`,
	}
	BRAF8 = Rule{
		Code:        "BR-AF-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-119", "BT-131", "BT-92", "BT-99"},
		Description: `For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "IGIC", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "IGIC" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).`,
	}
	BRAF9 = Rule{
		Code:        "BR-AF-09",
		Fields:      []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is "IGIC" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).`,
	}
	BRAF10 = Rule{
		Code:        "BR-AF-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "IGIC" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).`,
	}
	BRAG1 = Rule{
		Code:        "BR-AG-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "IPSI" shall contain in the VAT breakdown (BG-23) at least one VAT category code (BT-118) equal with "IPSI".`,
	}
	BRAG2 = Rule{
		Code:        "BR-AG-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "IPSI" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAG3 = Rule{
		Code:        "BR-AG-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "IPSI" shall contain the Seller VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAG4 = Rule{
		Code:        "BR-AG-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "IPSI" shall contain the Seller VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRAG5 = Rule{
		Code:        "BR-AG-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "IPSI" the Invoiced item VAT rate (BT-152) shall be 0 (zero) or greater than zero.`,
	}
	BRAG6 = Rule{
		Code:        "BR-AG-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "IPSI" the Document level allowance VAT rate (BT-96) shall be 0 (zero) or greater than zero.`,
	}
	BRAG7 = Rule{
		Code:        "BR-AG-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "IPSI" the Document level charge VAT rate (BT-103) shall be 0 (zero) or greater than zero.`,
	}
	BRAG8 = Rule{
		Code:        "BR-AG-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-119", "BT-131", "BT-92", "BT-99"},
		Description: `For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "IPSI", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "IPSI" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).`,
	}
	BRAG9 = Rule{
		Code:        "BR-AG-09",
		Fields:      []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is "IPSI" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).`,
	}
	BRAG10 = Rule{
		Code:        "BR-AG-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "IPSI" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).`,
	}
	BRB1 = Rule{
		Code:        "BR-B-01",
		Fields:      nil,
		Description: `An Invoice where the VAT category code (BT-151, BT-95 or BT-102) is “Split payment” shall be a domestic Italian invoice.`,
	}
	BRB2 = Rule{
		Code:        "BR-B-02",
		Fields:      []string{"BG-20", "BG-21", "BG-25"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is “Split payment" shall not contain an invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is “Standard rated”.`,
	}
	BRCO3 = Rule{
		Code:        "BR-CO-03",
		Fields:      []string{"BT-7", "BT-8"},
		Description: `Value added tax point date (BT-7) and Value added tax point date code (BT-8) are mutually exclusive.`,
	}
	BRCO4 = Rule{
		Code:        "BR-CO-04",
		Fields:      []string{"BG-25", "BT-151"},
		Description: `Each Invoice line (BG-25) shall be categorized with an Invoiced item VAT category code (BT-151).`,
	}
	BRCO5 = Rule{
		Code:        "BR-CO-05",
		Fields:      []string{"BT-97", "BT-98"},
		Description: `Document level allowance reason code (BT-98) and Document level allowance reason (BT-97) shall indicate the same type of allowance.`,
	}
	BRCO6 = Rule{
		Code:        "BR-CO-06",
		Fields:      []string{"BT-104", "BT-105"},
		Description: `Document level charge reason code (BT-105) and Document level charge reason (BT-104) shall indicate the same type of charge.`,
	}
	BRCO7 = Rule{
		Code:        "BR-CO-07",
		Fields:      []string{"BT-139", "BT-140"},
		Description: `Invoice line allowance reason code (BT-140) and Invoice line allowance reason (BT-139) shall indicate the same type of allowance reason.`,
	}
	BRCO8 = Rule{
		Code:        "BR-CO-08",
		Fields:      []string{"BT-144", "BT-145"},
		Description: `Invoice line charge reason code (BT-145) and Invoice line charge reason (BT-144) shall indicate the same type of charge reason.`,
	}
	BRCO9 = Rule{
		Code:        "BR-CO-09",
		Fields:      []string{"BT-31", "BT-48", "BT-63"},
		Description: `The Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) shall have a prefix in accordance with ISO code ISO 3166-1 alpha-2 by which the country of issue may be identified. Nevertheless, Greece may use the prefix ‘EL’.`,
	}
	BRCO10 = Rule{
		Code:        "BR-CO-10",
		Fields:      []string{"BT-106", "BT-131"},
		Description: `Sum of Invoice line net amount (BT-106) = Σ Invoice line net amount (BT-131).`,
	}
	BRCO11 = Rule{
		Code:        "BR-CO-11",
		Fields:      []string{"BT-107", "BT-92"},
		Description: `Sum of allowances on document level (BT-107) = Σ Document level allowance amount (BT-92).`,
	}
	BRCO12 = Rule{
		Code:        "BR-CO-12",
		Fields:      []string{"BT-108", "BT-99"},
		Description: `Sum of charges on document level (BT-108) = Σ Document level charge amount (BT-99).`,
	}
	BRCO13 = Rule{
		Code:        "BR-CO-13",
		Fields:      []string{"BT-107", "BT-108", "BT-109", "BT-131"},
		Description: `Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).`,
	}
	BRCO14 = Rule{
		Code:        "BR-CO-14",
		Fields:      []string{"BT-110", "BT-117"},
		Description: `Invoice total VAT amount (BT-110) = Σ VAT category tax amount (BT-117).`,
	}
	BRCO15 = Rule{
		Code:        "BR-CO-15",
		Fields:      []string{"BT-109", "BT-110", "BT-112"},
		Description: `Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).`,
	}
	BRCO16 = Rule{
		Code:        "BR-CO-16",
		Fields:      []string{"BT-112", "BT-113", "BT-114", "BT-115"},
		Description: `Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Paid amount (BT-113) +Rounding amount (BT-114).`,
	}
	BRCO17 = Rule{
		Code:        "BR-CO-17",
		Fields:      []string{"BT-116", "BT-117", "BT-119"},
		Description: `VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.`,
	}
	BRCO18 = Rule{
		Code:        "BR-CO-18",
		Fields:      []string{"BG-23"},
		Description: `An Invoice shall at least have one VAT breakdown group (BG-23).`,
	}
	BRCO19 = Rule{
		Code:        "BR-CO-19",
		Fields:      []string{"BG-14", "BT-73", "BT-74"},
		Description: `If Invoicing period (BG-14) is used, the Invoicing period start date (BT-73) or the Invoicing period end date (BT-74) shall be filled, or both.`,
	}
	BRCO20 = Rule{
		Code:        "BR-CO-20",
		Fields:      []string{"BG-26", "BT-134", "BT-135"},
		Description: `If Invoice line period (BG-26) is used, the Invoice line period start date (BT-134) or the Invoice line period end date (BT-135) shall be filled, or both.`,
	}
	BRCO21 = Rule{
		Code:        "BR-CO-21",
		Fields:      []string{"BG-20", "BT-97", "BT-98"},
		Description: `Each Document level allowance (BG-20) shall contain a Document level allowance reason (BT-97) or a Document level allowance reason code (BT-98), or both.`,
	}
	BRCO22 = Rule{
		Code:        "BR-CO-22",
		Fields:      []string{"BG-21", "BT-104", "BT-105"},
		Description: `Each Document level charge (BG-21) shall contain a Document level charge reason (BT-104) or a Document level charge reason code (BT-105), or both.`,
	}
	BRCO23 = Rule{
		Code:        "BR-CO-23",
		Fields:      []string{"BG-27", "BT-139", "BT-140"},
		Description: `Each Invoice line allowance (BG-27) shall contain an Invoice line allowance reason (BT-139) or an Invoice line allowance reason code (BT-140), or both.`,
	}
	BRCO24 = Rule{
		Code:        "BR-CO-24",
		Fields:      []string{"BG-28", "BT-144", "BT-145"},
		Description: `Each Invoice line charge (BG-28) shall contain an Invoice line charge reason (BT-144) or an Invoice line charge reason code (BT-145), or both.`,
	}
	BRCO25 = Rule{
		Code:        "BR-CO-25",
		Fields:      []string{"BT-115", "BT-20", "BT-9"},
		Description: `In case the Amount due for payment (BT-115) is positive, either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present.`,
	}
	BRCO26 = Rule{
		Code:        "BR-CO-26",
		Fields:      []string{"BT-29", "BT-30", "BT-31"},
		Description: `In order for the buyer to automatically identify a supplier, the Seller identifier (BT-29), the Seller legal registration identifier (BT-30) and/or the Seller VAT identifier (BT-31) shall be present.`,
	}
	BRCO27 = Rule{
		Code:        "BR-CO-27",
		Fields:      []string{"BT-84"},
		Description: `Either the IBAN or a Proprietary ID (BT-84) shall be used.`,
	}
	BRDEC1 = Rule{
		Code:        "BR-DEC-01",
		Fields:      []string{"BT-92"},
		Description: `The allowed maximum number of decimals for the Document level allowance amount (BT-92) is 2.`,
	}
	BRDEC2 = Rule{
		Code:        "BR-DEC-02",
		Fields:      []string{"BT-93"},
		Description: `The allowed maximum number of decimals for the Document level allowance base amount (BT-93) is 2.`,
	}
	BRDEC5 = Rule{
		Code:        "BR-DEC-05",
		Fields:      []string{"BT-99"},
		Description: `The allowed maximum number of decimals for the Document level charge amount (BT-99) is 2.`,
	}
	BRDEC6 = Rule{
		Code:        "BR-DEC-06",
		Fields:      []string{"BT-100"},
		Description: `The allowed maximum number of decimals for the Document level charge base amount (BT-100) is 2.`,
	}
	BRDEC9 = Rule{
		Code:        "BR-DEC-09",
		Fields:      []string{"BT-106"},
		Description: `The allowed maximum number of decimals for the Sum of Invoice line net amount (BT-106) is 2.`,
	}
	BRDEC10 = Rule{
		Code:        "BR-DEC-10",
		Fields:      []string{"BT-107"},
		Description: `The allowed maximum number of decimals for the Sum of allowanced on document level (BT-107) is 2.`,
	}
	BRDEC11 = Rule{
		Code:        "BR-DEC-11",
		Fields:      []string{"BT-108"},
		Description: `The allowed maximum number of decimals for the Sum of charges on document level (BT-108) is 2.`,
	}
	BRDEC12 = Rule{
		Code:        "BR-DEC-12",
		Fields:      []string{"BT-109"},
		Description: `The allowed maximum number of decimals for the Invoice total amount without VAT (BT-109) is 2.`,
	}
	BRDEC13 = Rule{
		Code:        "BR-DEC-13",
		Fields:      []string{"BT-110"},
		Description: `The allowed maximum number of decimals for the Invoice total VAT amount (BT-110) is 2.`,
	}
	BRDEC14 = Rule{
		Code:        "BR-DEC-14",
		Fields:      []string{"BT-112"},
		Description: `The allowed maximum number of decimals for the Invoice total amount with VAT (BT-112) is 2.`,
	}
	BRDEC15 = Rule{
		Code:        "BR-DEC-15",
		Fields:      []string{"BT-111"},
		Description: `The allowed maximum number of decimals for the Invoice total VAT amount in accounting currency (BT-111) is 2.`,
	}
	BRDEC16 = Rule{
		Code:        "BR-DEC-16",
		Fields:      []string{"BT-113"},
		Description: `The allowed maximum number of decimals for the Paid amount (BT-113) is 2.`,
	}
	BRDEC17 = Rule{
		Code:        "BR-DEC-17",
		Fields:      []string{"BT-114"},
		Description: `The allowed maximum number of decimals for the Rounding amount (BT-114) is 2.`,
	}
	BRDEC18 = Rule{
		Code:        "BR-DEC-18",
		Fields:      []string{"BT-115"},
		Description: `The allowed maximum number of decimals for the Amount due for payment (BT-115) is 2.`,
	}
	BRDEC19 = Rule{
		Code:        "BR-DEC-19",
		Fields:      []string{"BT-116"},
		Description: `The allowed maximum number of decimals for the VAT category taxable amount (BT-116) is 2.`,
	}
	BRDEC20 = Rule{
		Code:        "BR-DEC-20",
		Fields:      []string{"BT-117"},
		Description: `The allowed maximum number of decimals for the VAT category tax amount (BT-117) is 2.`,
	}
	BRDEC23 = Rule{
		Code:        "BR-DEC-23",
		Fields:      []string{"BT-131"},
		Description: `The allowed maximum number of decimals for the Invoice line net amount (BT-131) is 2.`,
	}
	BRDEC24 = Rule{
		Code:        "BR-DEC-24",
		Fields:      []string{"BT-136"},
		Description: `The allowed maximum number of decimals for the Invoice line allowance amount (BT-136) is 2.`,
	}
	BRDEC25 = Rule{
		Code:        "BR-DEC-25",
		Fields:      []string{"BT-137"},
		Description: `The allowed maximum number of decimals for the Invoice line allowance base amount (BT-137) is 2.`,
	}
	BRDEC27 = Rule{
		Code:        "BR-DEC-27",
		Fields:      []string{"BT-141"},
		Description: `The allowed maximum number of decimals for the Invoice line charge amount (BT-141) is 2.`,
	}
	BRDEC28 = Rule{
		Code:        "BR-DEC-28",
		Fields:      []string{"BT-142"},
		Description: `The allowed maximum number of decimals for the Invoice line charge base amount (BT-142) is 2.`,
	}
	BRE1 = Rule{
		Code:        "BR-E-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Exempt from VAT" shall contain exactly one VAT breakdown (BG-23) with the VAT category code (BT-118) equal to "Exempt from VAT".`,
	}
	BRE2 = Rule{
		Code:        "BR-E-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Exempt from VAT" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRE3 = Rule{
		Code:        "BR-E-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Exempt from VAT" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRE4 = Rule{
		Code:        "BR-E-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Exempt from VAT" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRE5 = Rule{
		Code:        "BR-E-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Exempt from VAT", the Invoiced item VAT rate (BT-152) shall be 0 (zero).`,
	}
	BRE6 = Rule{
		Code:        "BR-E-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Exempt from VAT", the Document level allowance VAT rate (BT-96) shall be 0 (zero).`,
	}
	BRE7 = Rule{
		Code:        "BR-E-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Exempt from VAT", the Document level charge VAT rate (BT-103) shall be 0 (zero).`,
	}
	BRE8 = Rule{
		Code:        "BR-E-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Exempt from VAT" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Exempt from VAT".`,
	}
	BRE9 = Rule{
		Code:        "BR-E-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) In a VAT breakdown (BG-23) where the VAT category code (BT-118) equals "Exempt from VAT" shall equal 0 (zero).`,
	}
	BRE10 = Rule{
		Code:        "BR-E-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Exempt from VAT" shall have a VAT exemption reason code (BT-121) or a VAT exemption reason text (BT-120).`,
	}
	BRG1 = Rule{
		Code:        "BR-G-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Export outside the EU" shall contain in the VAT breakdown (BG-23) exactly one VAT category code (BT-118) equal with "Export outside the EU".`,
	}
	BRG2 = Rule{
		Code:        "BR-G-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Export outside the EU" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRG3 = Rule{
		Code:        "BR-G-03",
		Fields:      []string{"BG-20", "BT-31", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Export outside the EU" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRG4 = Rule{
		Code:        "BR-G-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Export outside the EU" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRG5 = Rule{
		Code:        "BR-G-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Export outside the EU" the Invoiced item VAT rate (BT-152) shall be 0 (zero).`,
	}
	BRG6 = Rule{
		Code:        "BR-G-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Export outside the EU" the Document level allowance VAT rate (BT-96) shall be 0 (zero).`,
	}
	BRG7 = Rule{
		Code:        "BR-G-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Export outside the EU" the Document level charge VAT rate (BT-103) shall be 0 (zero).`,
	}
	BRG8 = Rule{
		Code:        "BR-G-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Export outside the EU" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Export outside the EU".`,
	}
	BRG9 = Rule{
		Code:        "BR-G-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Export outside the EU" shall be 0 (zero).`,
	}
	BRG10 = Rule{
		Code:        "BR-G-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with the VAT Category code (BT-118) "Export outside the EU" shall have a VAT exemption reason code (BT-121), meaning "Export outside the EU" or the VAT exemption reason text (BT-120) "Export outside the EU" (or the equivalent standard text in another language).`,
	}
	BRIC1 = Rule{
		Code:        "BR-IC-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Intra-community supply" shall contain in the VAT breakdown (BG-23) exactly one VAT category code (BT-118) equal with "Intra-community supply".`,
	}
	BRIC2 = Rule{
		Code:        "BR-IC-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-48", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Intra-community supply" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48).`,
	}
	BRIC3 = Rule{
		Code:        "BR-IC-03",
		Fields:      []string{"BG-20", "BT-31", "BT-48", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Intra-community supply" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48).`,
	}
	BRIC4 = Rule{
		Code:        "BR-IC-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-48", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Intra-community supply" shall contain the Seller VAT Identifier (BT-31) or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48).`,
	}
	BRIC5 = Rule{
		Code:        "BR-IC-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Intracommunity supply" the Invoiced item VAT rate (BT-152) shall be 0 (zero).`,
	}
	BRIC6 = Rule{
		Code:        "BR-IC-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Intra-community supply" the Document level allowance VAT rate (BT-96) shall be 0 (zero).`,
	}
	BRIC7 = Rule{
		Code:        "BR-IC-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Intra-community supply" the Document level charge VAT rate (BT-103) shall be 0 (zero).`,
	}
	BRIC8 = Rule{
		Code:        "BR-IC-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Intra-community supply" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Intra-community supply".`,
	}
	BRIC9 = Rule{
		Code:        "BR-IC-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Intra-community supply" shall be 0 (zero).`,
	}
	BRIC10 = Rule{
		Code:        "BR-IC-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with the VAT Category code (BT-118) "Intra-community supply" shall have a VAT exemption reason code (BT-121), meaning "Intra-community supply" or the VAT exemption reason text (BT-120) "Intra-community supply" (or the equivalent standard text in another language).`,
	}
	BRIC11 = Rule{
		Code:        "BR-IC-11",
		Fields:      []string{"BG-14", "BG-23", "BT-118", "BT-72"},
		Description: `In an Invoice with a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Intra-community supply" the Actual delivery date (BT-72) or the Invoicing period (BG-14) shall not be blank.`,
	}
	BRIC12 = Rule{
		Code:        "BR-IC-12",
		Fields:      []string{"BG-23", "BT-118", "BT-80"},
		Description: `In an Invoice with a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Intra-community supply" the Deliver to country code (BT-80) shall not be blank.`,
	}
	BRO1 = Rule{
		Code:        "BR-O-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Not subject to VAT" shall contain exactly one VAT breakdown group (BG-23) with the VAT category code (BT-118) equal to "Not subject to VAT".`,
	}
	BRO2 = Rule{
		Code:        "BR-O-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-48", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Not subject to VAT" shall not contain the Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer VAT identifier (BT-48).`,
	}
	BRO3 = Rule{
		Code:        "BR-O-03",
		Fields:      []string{"BG-20", "BT-31", "BT-48", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Not subject to VAT" shall not contain the Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer VAT identifier (BT-48).`,
	}
	BRO4 = Rule{
		Code:        "BR-O-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-48", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Not subject to VAT" shall not contain the Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer VAT identifier (BT-48).`,
	}
	BRO5 = Rule{
		Code:        "BR-O-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `An Invoice line (BG-25) where the VAT category code (BT-151) is "Not subject to VAT" shall not contain an Invoiced item VAT rate (BT-152).`,
	}
	BRO6 = Rule{
		Code:        "BR-O-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `A Document level allowance (BG-20) where VAT category code (BT-95) is "Not subject to VAT" shall not contain a Document level allowance VAT rate (BT-96).`,
	}
	BRO7 = Rule{
		Code:        "BR-O-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `A Document level charge (BG-21) where the VAT category code (BT-102) is "Not subject to VAT" shall not contain a Document level charge VAT rate (BT-103).`,
	}
	BRO8 = Rule{
		Code:        "BR-O-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where the VAT category code (BT-118) is " Not subject to VAT" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Not subject to VAT".`,
	}
	BRO9 = Rule{
		Code:        "BR-O-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where the VAT category code (BT-118) is "Not subject to VAT" shall be 0 (zero).`,
	}
	BRO10 = Rule{
		Code:        "BR-O-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) " Not subject to VAT" shall have a VAT exemption reason code (BT-121), meaning " Not subject to VAT" or a VAT exemption reason text (BT-120) " Not subject to VAT" (or the equivalent standard text in another language).`,
	}
	BRO11 = Rule{
		Code:        "BR-O-11",
		Fields:      []string{"BG-23", "BT-118"},
		Description: `An Invoice that contains a VAT breakdown group (BG-23) with a VAT category code (BT-118) "Not subject to VAT" shall not contain other VAT breakdown groups (BG-23).`,
	}
	BRO12 = Rule{
		Code:        "BR-O-12",
		Fields:      []string{"BG-23", "BG-25", "BT-118", "BT-151"},
		Description: `An Invoice that contains a VAT breakdown group (BG-23) with a VAT category code (BT-118) "Not subject to VAT" shall not contain an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is not "Not subject to VAT".`,
	}
	BRO13 = Rule{
		Code:        "BR-O-13",
		Fields:      []string{"BG-20", "BG-23", "BT-118", "BT-95"},
		Description: `An Invoice that contains a VAT breakdown group (BG-23) with a VAT category code (BT-118) "Not subject to VAT" shall not contain Document level allowances (BG-20) where Document level allowance VAT category code (BT-95) is not "Not subject to VAT".`,
	}
	BRO14 = Rule{
		Code:        "BR-O-14",
		Fields:      []string{"BG-21", "BG-23", "BT-102", "BT-118"},
		Description: `An Invoice that contains a VAT breakdown group (BG-23) with a VAT category code (BT-118) "Not subject to VAT" shall not contain Document level charges (BG-21) where Document level charge VAT category code (BT-102) is not "Not subject to VAT".`,
	}
	BRS1 = Rule{
		Code:        "BR-S-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Standard rated" shall contain in the VAT breakdown (BG-23) at least one VAT category code (BT-118) equal with "Standard rated".`,
	}
	BRS2 = Rule{
		Code:        "BR-S-02",
		Fields:      []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Standard rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRS3 = Rule{
		Code:        "BR-S-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Standard rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRS4 = Rule{
		Code:        "BR-S-04",
		Fields:      []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Standard rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRS5 = Rule{
		Code:        "BR-S-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Standard rated" the Invoiced item VAT rate (BT-152) shall be greater than zero.`,
	}
	BRS6 = Rule{
		Code:        "BR-S-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Standard rated" the Document level allowance VAT rate (BT-96) shall be greater than zero.`,
	}
	BRS7 = Rule{
		Code:        "BR-S-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Standard rated" the Document level charge VAT rate (BT-103) shall be greater than zero.`,
	}
	BRS8 = Rule{
		Code:        "BR-S-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-119", "BT-131", "BT-92", "BT-99"},
		Description: `For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard rated", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "Standard rated" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).`,
	}
	BRS9 = Rule{
		Code:        "BR-S-09",
		Fields:      []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is "Standard rated" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).`,
	}
	BRS10 = Rule{
		Code:        "BR-S-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Standard rate" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).`,
	}
	BRZ1 = Rule{
		Code:        "BR-Z-01",
		Fields:      []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-118"},
		Description: `An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is "Zero rated" shall contain in the VAT breakdown (BG-23) exactly one VAT category code (BT-118) equal with "Zero rated".`,
	}
	BRZ2 = Rule{
		Code:        "BR-Z-02",
		Fields:      []string{"BT-151", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains an Invoice line where the Invoiced item VAT category code (BT-151) is "Zero rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRZ3 = Rule{
		Code:        "BR-Z-03",
		Fields:      []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"},
		Description: `An Invoice that contains a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Zero rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRZ4 = Rule{
		Code:        "BR-Z-04",
		Fields:      []string{"BT-102", "BT-31", "BT-32", "BT-63"},
		Description: `An Invoice that contains a Document level charge where the Document level charge VAT category code (BT-102) is "Zero rated" shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63).`,
	}
	BRZ5 = Rule{
		Code:        "BR-Z-05",
		Fields:      []string{"BG-25", "BT-151", "BT-152"},
		Description: `In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Zero rated" the Invoiced item VAT rate (BT-152) shall be 0 (zero).`,
	}
	BRZ6 = Rule{
		Code:        "BR-Z-06",
		Fields:      []string{"BG-20", "BT-95", "BT-96"},
		Description: `In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Zero rated" the Document level allowance VAT rate (BT-96) shall be 0 (zero).`,
	}
	BRZ7 = Rule{
		Code:        "BR-Z-07",
		Fields:      []string{"BG-21", "BT-102", "BT-103"},
		Description: `In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is "Zero rated" the Document level charge VAT rate (BT-103) shall be 0 (zero).`,
	}
	BRZ8 = Rule{
		Code:        "BR-Z-08",
		Fields:      []string{"BG-23", "BT-116", "BT-118", "BT-131", "BT-92", "BT-99"},
		Description: `In a VAT breakdown (BG-23) where VAT category code (BT-118) is "Zero rated" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amount (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Zero rated".`,
	}
	BRZ9 = Rule{
		Code:        "BR-Z-09",
		Fields:      []string{"BG-23", "BT-117", "BT-118"},
		Description: `The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is "Zero rated" shall equal 0 (zero).`,
	}
	BRZ10 = Rule{
		Code:        "BR-Z-10",
		Fields:      []string{"BG-23", "BT-118", "BT-120", "BT-121"},
		Description: `A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Zero rated" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).`,
	}
)
