// Code generated by genrules from EN16931-CII-model.sch; DO NOT EDIT.
// Source: https://github.com/ConnectingEurope/eInvoicing-EN16931
// Version: 2.4.0
// Generated: 2025-10-21T13:47:34Z

package rules

var (
	BRDE1 = Rule{
		Code:        "BR-DE-1",
		Fields:      []string{"BG-16"},
		Description: `Eine Rechnung (INVOICE) muss Angaben zu "PAYMENT INSTRUCTIONS" (BG-16) enthalten.`,
	}
	BRDE10 = Rule{
		Code:        "BR-DE-10",
		Fields:      []string{"BG-15", "BT-77"},
		Description: `Das Element "Deliver to city" (BT-77) muss übermittelt werden, wenn die Gruppe "DELIVER TO ADDRESS" (BG-15) übermittelt wird.`,
	}
	BRDE11 = Rule{
		Code:        "BR-DE-11",
		Fields:      []string{"BG-15", "BT-78"},
		Description: `Das Element "Deliver to post code" (BT-78) muss übermittelt werden, wenn die Gruppe "DELIVER TO ADDRESS" (BG-15) übermittelt wird.`,
	}
	BRDE14 = Rule{
		Code:        "BR-DE-14",
		Fields:      []string{"BT-119"},
		Description: `Das Element "VAT category rate" (BT-119) muss übermittelt werden.`,
	}
	BRDE15 = Rule{
		Code:        "BR-DE-15",
		Fields:      []string{"BT-10"},
		Description: `Das Element "Buyer reference" (BT-10) muss übermittelt werden.`,
	}
	BRDE16 = Rule{
		Code:        "BR-DE-16",
		Fields:      []string{"BG-11", "BT-31", "BT-32"},
		Description: `Wenn in einer Rechnung die Steuercodes S, Z, E, AE, K, G, L oder M verwendet werden, muss mindestens eines der Elemente "Seller VAT identifier" (BT-31), "Seller tax registration identifier" (BT-32) oder "SELLER TAX REPRESENTATIVE PARTY" (BG-11) übermittelt werden.`,
	}
	BRDE17 = Rule{
		Code:        "BR-DE-17",
		Fields:      []string{"BT-3"},
		Description: `Mit dem Element "Invoice type code" (BT-3) sollen ausschließlich folgende Codes aus der Codeliste UNTDID 1001 übermittelt werden: 326 (Partial invoice), 380 (Commercial invoice), 384 (Corrected invoice), 389 (Self-billed invoice) und 381 (Credit note),875 (Partial construction invoice), 876 (Partial final construction invoice), 877 (Final construction invoice).`,
	}
	BRDE18 = Rule{
		Code:        "BR-DE-18",
		Fields:      []string{"BT-20"},
		Description: `Skonto Zeilen in muessen diesem regulärem Ausdruck entsprechen: . Die Informationen zur Gewährung von Skonto müssen wie folgt im Element "Payment terms" (BT-20) übermittelt werden: Anzugeben ist im ersten Segment "SKONTO", im zweiten "TAGE=n", im dritten "PROZENT=n". Prozentzahlen sind ohne Vorzeichen sowie mit Punkt getrennt von zwei Nachkommastellen anzugeben. Liegt dem zu berechnenden Betrag nicht BT-115, "fälliger Betrag" zugrunde, sondern nur ein Teil des fälligen Betrags der Rechnung, ist der Grundwert zur Berechnung von Skonto als viertes Segment "BASISBETRAG=n" gemäß dem semantischen Datentypen Amount anzugeben. Jeder Eintrag beginnt mit einer #, die Segmente sind mit einer # getrennt und eine Zeile schließt mit einer # ab. Am Ende einer vollständigen Skontoangabe muss ein XML-konformer Zeilenumbruch folgen. Alle Angaben zur Gewährung von Skonto müssen in Großbuchstaben gemacht werden. Zusätzliches Whitespace (Leerzeichen, Tabulatoren oder Zeilenumbrüche) ist nicht zulässig. Andere Zeichen oder Texte als in den oberen Vorgaben genannt sind nicht zulässig.`,
	}
	BRDE19 = Rule{
		Code:        "BR-DE-19",
		Fields:      []string{"BT-81", "BT-84"},
		Description: `"Payment account identifier" (BT-84) soll eine korrekte IBAN enthalten, wenn in "Payment means type code" (BT-81) mit dem Code 58 SEPA als Zahlungsmittel gefordert wird.`,
	}
	BRDE2 = Rule{
		Code:        "BR-DE-2",
		Fields:      []string{"BG-6"},
		Description: `Die Gruppe "SELLER CONTACT" (BG-6) muss übermittelt werden.`,
	}
	BRDE20 = Rule{
		Code:        "BR-DE-20",
		Fields:      []string{"BT-81", "BT-91"},
		Description: `"Debited account identifier" (BT-91) soll eine korrekte IBAN enthalten, wenn in "Payment means type code" (BT-81) mit dem Code 59 SEPA als Zahlungsmittel gefordert wird.`,
	}
	BRDE21 = Rule{
		Code:        "BR-DE-21",
		Fields:      []string{"BT-24"},
		Description: `Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.`,
	}
	BRDE22 = Rule{
		Code:        "BR-DE-22",
		Fields:      nil,
		Description: `Not all filename attributes of the embeddedDocumentBinaryObject elements are unique`,
	}
	BRDE23A = Rule{
		Code:        "BR-DE-23-a",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Überweisungen enthält (30, 58), muss BG-17 "CREDIT TRANSFER" übermittelt werden.`,
	}
	BRDE23B = Rule{
		Code:        "BR-DE-23-b",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Überweisungen enthält (30, 58), dürfen BG-18 und BG-19 nicht übermittelt werden.`,
	}
	BRDE24A = Rule{
		Code:        "BR-DE-24-a",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Kartenzahlungen enthält (48, 54, 55), muss genau BG-18 "PAYMENT CARD INFORMATION" übermittelt werden.`,
	}
	BRDE24B = Rule{
		Code:        "BR-DE-24-b",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Kartenzahlungen enthält (48, 54, 55), dürfen BG-17 und BG-19 nicht übermittelt werden.`,
	}
	BRDE25A = Rule{
		Code:        "BR-DE-25-a",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Lastschriften enthält (59), muss genau BG-19 "DIRECT DEBIT" übermittelt werden.`,
	}
	BRDE25B = Rule{
		Code:        "BR-DE-25-b",
		Fields:      nil,
		Description: `Wenn BT-81 "Payment means type code" einen Schlüssel für Lastschriften enthält (59), dürfen BG-17 und BG-18 nicht übermittelt werden.`,
	}
	BRDE26 = Rule{
		Code:        "BR-DE-26",
		Fields:      []string{"BT-3"},
		Description: `Wenn im Element Invoice type code (BT-3) der Code 384 (Corrected invoice) übergeben wird, soll PRECEDING INVOICE REFERENCE BG-3 mind. einmal vorhanden sein.`,
	}
	BRDE27 = Rule{
		Code:        "BR-DE-27",
		Fields:      nil,
		Description: `In BT-42 sollen mindestens drei Ziffern enthalten sein.`,
	}
	BRDE28 = Rule{
		Code:        "BR-DE-28",
		Fields:      nil,
		Description: `In BT-43 soll genau ein @-Zeichen enthalten sein, welches nicht von einem Leerzeichen, einem Punkt, aber mindestens zwei Zeichen auf beiden Seiten flankiert werden soll. Ein Punkt sollte nicht am Anfang oder am Ende stehen.`,
	}
	BRDE3 = Rule{
		Code:        "BR-DE-3",
		Fields:      []string{"BT-37"},
		Description: `Das Element "Seller city" (BT-37) muss übermittelt werden.`,
	}
	BRDE30 = Rule{
		Code:        "BR-DE-30",
		Fields:      nil,
		Description: `Wenn "DIRECT DEBIT" BG-19 vorhanden ist, dann muss "Bank assigned creditor identifier" BT-90 übermittelt werden.`,
	}
	BRDE31 = Rule{
		Code:        "BR-DE-31",
		Fields:      nil,
		Description: `Wenn "DIRECT DEBIT" BG-19 vorhanden ist, dann muss "Debited account identifier" BT-91 übermittelt werden.`,
	}
	BRDE4 = Rule{
		Code:        "BR-DE-4",
		Fields:      []string{"BT-38"},
		Description: `Das Element "Seller post code" (BT-38) muss übermittelt werden.`,
	}
	BRDE5 = Rule{
		Code:        "BR-DE-5",
		Fields:      []string{"BT-41"},
		Description: `Das Element "Seller contact point" (BT-41) muss übermittelt werden.`,
	}
	BRDE6 = Rule{
		Code:        "BR-DE-6",
		Fields:      []string{"BT-42"},
		Description: `Das Element "Seller contact telephone number" (BT-42) muss übermittelt werden.`,
	}
	BRDE7 = Rule{
		Code:        "BR-DE-7",
		Fields:      []string{"BT-43"},
		Description: `Das Element "Seller contact email address" (BT-43) muss übermittelt werden.`,
	}
	BRDE8 = Rule{
		Code:        "BR-DE-8",
		Fields:      []string{"BT-52"},
		Description: `Das Element "Buyer city" (BT-52) muss übermittelt werden.`,
	}
	BRDE9 = Rule{
		Code:        "BR-DE-9",
		Fields:      []string{"BT-53"},
		Description: `Das Element "Buyer post code" (BT-53) muss übermittelt werden.`,
	}
	BRDECVD1 = Rule{
		Code:        "BR-DE-CVD-01",
		Fields:      []string{"BT-12"},
		Description: `[BR-DE-CVD-01] Das Element "Contract reference" (BT-12) muss übermittelt werden.`,
	}
	BRDECVD2 = Rule{
		Code:        "BR-DE-CVD-02",
		Fields:      []string{"BT-17"},
		Description: `[BR-DE-CVD-02] Das Element "Tender or lot reference" (BT-17) muss übermittelt werden.`,
	}
	BRDECVD3 = Rule{
		Code:        "BR-DE-CVD-03",
		Fields:      []string{"BG-25", "BT-158", "BT-160"},
		Description: `[BR-DE-CVD-03] In einer Rechnung muss mindestens eine INVOICE LINE (BG-25) enthalten sein, in der der Scheme identifier von "Item classification identifier" (BT-158) den Wert 'CVD' und der "Item attribute name" (BT-160) den Wert 'cva' enthält.`,
	}
	BRDECVD4 = Rule{
		Code:        "BR-DE-CVD-04",
		Fields:      []string{"BT-158"},
		Description: `[BR-DE-CVD-04] Ein "Item classification identifier" (BT-158) mit dem Scheme identifier 'CVD' muss einen Wert aus der Liste der zulässigen Fahrzeugkategorien enthalten.`,
	}
	BRDECVD5 = Rule{
		Code:        "BR-DE-CVD-05",
		Fields:      []string{"BG-32", "BT-160", "BT-161"},
		Description: `[BR-DE-CVD-05] Wenn innerhalb von ITEM ATTRIBUTES (BG-32) der "Item attribute name" (BT-160) den Wert 'cva' hat, muss der "Item attribute value" (BT-161) einen der zulässigen Werte enthalten.`,
	}
	BRDECVD6A = Rule{
		Code:        "BR-DE-CVD-06-a",
		Fields:      []string{"BT-158", "BT-160"},
		Description: `[BR-DE-CVD-06-a] Wenn der Scheme identifier von "Item classification identifier" (BT-158) mit dem Wert 'CVD' angegeben ist, muss in derselben Rechnungszeile genau ein "Item attribute name" (BT-160) mit dem Wert 'cva' vorhanden sein.`,
	}
	BRDECVD6B = Rule{
		Code:        "BR-DE-CVD-06-b",
		Fields:      []string{"BT-158", "BT-160"},
		Description: `[BR-DE-CVD-06-b] Wenn "Item attribute name" (BT-160) mit dem Wert 'cva' angegeben ist, muss in derselben Rechnungszeile genau ein "Item classification identifier" (BT-158) mit dem Scheme identifier 'CVD' vorhanden sein.`,
	}
	BRDETMP32 = Rule{
		Code:        "BR-DE-TMP-32",
		Fields:      nil,
		Description: `[BR-DE-TMP-32] Eine Rechnung sollte zur Angabe des Liefer-/Leistungsdatums entweder BT-72 "Actual delivery date", BG-14 "Invoicing period" oder in jeder Rechnungsposition BG-26 "Invoice line period" enthalten.`,
	}
	BRDEX1 = Rule{
		Code:        "BR-DEX-01",
		Fields:      []string{"BT-125"},
		Description: `Das Element "Attached Document" (BT-125) benutzt einen nicht zulässigen MIME-Code: . Im Falle einer Extension darf zusätzlich zu der Liste der mime codes (definiert in Abschnitt 8.2, "Binary Object") der MIME-Code application/xml genutzt werden.`,
	}
	BRDEX4 = Rule{
		Code:        "BR-DEX-04",
		Fields:      nil,
		Description: `Any scheme identifier in MUST be coded using one of the ISO 6523 ICD list.`,
	}
	BRDEX5 = Rule{
		Code:        "BR-DEX-05",
		Fields:      nil,
		Description: `Any scheme identifier in MUST be coded using one of the ISO 6523 ICD list.`,
	}
	BRDEX6 = Rule{
		Code:        "BR-DEX-06",
		Fields:      nil,
		Description: `Any scheme identifier in MUST be coded using one of the ISO 6523 ICD list.`,
	}
	BRDEX7 = Rule{
		Code:        "BR-DEX-07",
		Fields:      nil,
		Description: `Any scheme identifier for an Endpoint Identifier in MUST belong to the CEF EAS code list.`,
	}
	BRDEX8 = Rule{
		Code:        "BR-DEX-08",
		Fields:      nil,
		Description: `Any scheme identifier for a Delivery location identifier in MUST be coded using one of the ISO 6523 ICD list.`,
	}
	BRDEX15 = Rule{
		Code:        "BR-DEX-15",
		Fields:      nil,
		Description: `[BR-DEX-15] This CII file might use the concept of Sub Invoice Lines. However XRechnung does not support this.`,
	}
	BRTMP2 = Rule{
		Code:        "BR-TMP-2",
		Fields:      nil,
		Description: `BT-124 "External document location" muss eine absolute URL mit gültigem Schema enthalten.`,
	}
	BRTMP3 = Rule{
		Code:        "BR-TMP-3",
		Fields:      nil,
		Description: `If both elements to which BT-149 and BT-150 can be mapped are present, both must be equal.`,
	}
	BRTMPCVD1 = Rule{
		Code:        "BR-TMP-CVD-01",
		Fields:      []string{"BT-158"},
		Description: `[BR-TMP-CVD-01] Das Bildungsschema für "Item classification identifier" (BT-158) ist aus der Codeliste UNTDID 7143 zu wählen.`,
	}
)
